---
   - name: create an address
     gcp_compute_address:
         name: "{{ instance_address }}"
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         state: present
     register: address
