---
# tasks file for gcp_instance
   - name: create a disk
     gcp_compute_disk:
         name: "{{ instance_disk }}"
         size_gb: 10
         source_image: 'projects/debian-cloud/global/images/family/debian-9'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
