---
   - name: create an address
     gcp_compute_address:
         name: "{{ item }}"
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         state: present
     with_items: "{{ instance_address }}"
     when: instance_address is defined
     register: address
