- name: create an allow firewall rule
  gcp_compute_firewall:
      name: "{{ fw_rule_name }}"
      allowed:
      - ip_protocol: "{{ fw_protocol }}"
        ports:
        - "{{ fw_port }}"
      target_tags:
      - "{{ fw_target_tags }}"
      source_ranges:
      - "{{ fw_src_range }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: "{{ fw_state }}"
