---
   - name: create an instance
     gcp_compute_instance:
         state: present
         name: "{{ instance_name }}"
         can_ip_forward: yes
         machine_type: f1-micro
         metadata:
             serial-port-enable: 1
             enable-oslogin: TRUE
         disks:
             - auto_delete: true
               boot: true
               source: "{{ disk }}"
         network_interfaces:
             - access_configs:
               - name: External NAT
                 nat_ip: "{{ address }}"
                 type: ONE_TO_ONE_NAT
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance
