- name: create an allowed firewall rule to port 80
  gcp_compute_firewall:
      name: "{{ gcp_fw_name }}"
      allowed:
      - ip_protocol: tcp
        ports:
        - '80'
      source_ranges:
      - 80.232.241.24
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
  when: gcp_fw_name is defined
