- name: Save host data
  add_host:
    ansible_ssh_host: "{{ item.public_ip }}"
    hostname: "{{ item.name }}"
    groupname: "{{ item.name[:-2] }}s"
    ansible_ssh_private_ip: "{{ item.private_ip }}"
  with_items: "{{ gce.instance_data }}"
