---

dependencies: []

galaxy_info:
  role_name: 'sqlite'
  author: 'Adfinis SyGroup AG'
  description: 'Install and manage sqlite.'
  company: 'Adfinis SyGroup AG'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - sqlite
    - sql
