---

- name: install sqlite related packages
  package:
    name: '{{ sqlite_packages }}'
    state: present

- name: create sqlite data directory
  file:
    path: '{{ sqlite_datadir }}'
    owner: root
    group: root
    mode: 0755
    state: directory
    seuser: system_u
    serole: object_r
    setype: unconfined_t
    selevel: s0
