- name: Create group for mysql db
  group:
    name: "{{ mysql_user_name }}"
    state: present

- name: Create user for mysql db
  user:
    name: "{{ mysql_user_name }}"
    group: "{{ mysql_user_name }}"
    state: present
