- name: Create bastion instance
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    instance_names:
      - bastion01
    instance_addresses: "{{ instance_name }}"
  roles:
    - role: gcp_instance
      instance_name: "{{ instance_names }}"
      instance_address: "{{ instance_addresses }}"
    - role: bastion
