- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
      gcp_project: rational-lambda-233119
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /vagrant/rational-lambda-233119-8109e997ed2f.json
      zone: "europe-north1-a"
      region: "europe-north1"

  tasks:
   - name: create a network
     gcp_compute_network:
         name: 'network-instance'
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: network
   - name: create a address
     gcp_compute_address:
         name: "address-instance"
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: test-vm
         can_ip_forward: yes
         machine_type: f1-micro
         disks:
           - auto_delete: true
             boot: true
             initialize_params:
               source_image: 'projects/debian-cloud/global/images/family/debian-9-stretch-v20190213'
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
               - name: External NAT
                 nat_ip: "{{ address }}"
                 type: ONE_TO_ONE_NAT
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance
