- name: Create web and db instances
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    instance_names:
      - web-server01
      - web-server02
      - db-server01
  roles:
    - role: gcp_instance
      instance_name: "{{ instance_names }}"

#- name: Manage web-servers instances
#  hosts: web-servers
#  gather_facts: yes
#  connection: ssh
#  become: True
#  roles:
#    - vitalk.flaskapp

#- name: Manage db-servers instances
#  hosts: db-servers
#  connection: ssh
#  become: True
#  roles:
#    - geerlingguy.mysql
