- name: Compute Engine Instance
  hosts: localhost
  vars:
    instance_name: webserver01,webserver02,dbserver01
    gcp_lb_name: flaskapp
    gcp_fw_name: flaskapphttp80allow
  roles:
    - role: gcp
      instance_names: "{{ instance_name }}"

- name: Install python, pip and flask
  hosts: webservers
  roles:
    - role: andrewrothstein.flask
  become: true

- name: Install mysql
  hosts: dbservers
  roles:
    - role: geerlingguy.mysql
  become: true

- name: Install flaskapp for dbservers
  hosts: dbservers
  roles:
    - role: flaskapp
  become: true

- name: Install flaskapp for webservers
  hosts: webservers
  roles:
    - role: flaskapp
  become: true
